---
title: Choose a License
description: Non-judgmental guidance on choosing a license for your open source project
relative_permalinks: false
markdown: kramdown
url: "http://choosealicense.com"

collections:
  licenses:
    output: true
    permalink: /licenses/:path/

defaults:
  -
    scope:
      path: ""
      type: "licenses"
    values:
      layout: license
      featured: false
      hidden: false
      variant: false

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/clipboard/test

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  
sass:
    sass_dir: _sass
    style: :compressed

twitter:
  username: "@github"
