# Each license has YAML front matter describing the license's properties.
# The available fields are:

- name: title
  description: The SPDX-compliant, human-readable license name
  required: true

- name: source
  description: The URL to the license source text
  required: true

- name: description
  description: A human-readable description of the license
  required: true

- name: how
  description: Instructions on how to implement the license
  required: true

- name: required
  description: Bulleted list of required rules
  required: true

- name: permitted
  description: Bulleted list of permitted rules
  required: true

- name: forbidden
  description: Bulleted list of forbidden rules
  required: true

# Optional fields

- name: note
  description: Additional information about the licenses
  required: false

- name: using
  description: 'A list of notable projects using the license in the form of `project_name: "url"`'
  required: false

- name: hidden
  description: Whether the license is hidden from the license list (defaults to true)
  required: false

- name: redirect_from
  description: Relative path(s) to redirect to the license from, to prevent breaking old URLs
  required: false

- name: featured
  description: Whether the license should be featured on the main page (defaults to false)
  required: false

- name: nickname
  description: A shorter, human-readable license name where the SPDX license name (`title` above) is long
  required: false

- name: variant
  description: Whether the license is a variant of a family of licenses (defaults to false)
  required: false

- name: family
  description: If part of a license family, the name of the license family (e.g., `GPL`)
  required: false

- name: tab-slug
  description: If part of a license family, a license slug containing only `a-z`, `0-9`, and `_` characters, used for internal links on the licenses page
  required: false
